### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED 

### ISSUE THREAD

**Issue by neatlife** [creativetimofficial/ct-paper-kit-pro#1]
http://www.creative-tim.com/assets/application-22c027852a4f6c36a594fa0d80820026.js Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
mentions-and-photoswipe-b51ac76a67c18dc5cb67f5c897135c16.js:1 Uncaught ReferenceError: jQuery is not defined
paper-kit-pro:1216 Uncaught ReferenceError: $ is not defined
5paper-kit-pro:959 Uncaught ReferenceError: toggleCommentsArea is not defined

**Comment by alexandru-paduraru** [comment]
@su-xiaolin thank you for the information. Can you please tell us where did you get that error? It looks like you have a link from Creative-tim.com which is not included in Paper Kit PRO. 

Best,
Alex

**Comment by neatlife** [comment]
I am sorry.
