### ISSUE TITLE
Alignment of dropdown 

### ISSUE THREAD

**Issue by be-cobblestone** [creativetimofficial/ct-paper-kit-pro#2]
When using dropdowns in collapseable menus like in the search-with-sidebar.html example the item below the dropdown is pushed to the right. This happens only when screen resolution > 768 px. 
See the updated example in the zip file and screenshots from chromium
[search-with-sidebar-jdp.html.zip](https://github.com/timcreative/paper-kit-pro/files/72651/search-with-sidebar-jdp.html.zip)
With less than 768px the items below the dropdown align correctly
![less768px](https://cloud.githubusercontent.com/assets/16451377/12009963/5cec5c4e-ac91-11e5-8822-aa243edac797.png)
On larger screens the itmes below the dropdown are pushed to the right
![more768px](https://cloud.githubusercontent.com/assets/16451377/12009965/6042a54c-ac91-11e5-951e-2c7555d39d3c.png)

**Comment by alexandru-paduraru** [comment]
@be-cobblestone thank you for being our customer. We checked the example and you're right, we have a bug with the dropdowns inside the Burger Menu. We will have a look as soon as we get back to the office (3-4 Jan 2016, we are in a small vacation now) and we will come with a quick fix for this issue. 

All the best,
Alex

**Comment by alexandru-paduraru** [comment]
Issue fixed in V1.0.1 and is available for download on your dashboard on http://www.creative-tim.com

Thank you again for pointing out.
