### ISSUE TITLE
Problem with notification classes

### ISSUE THREAD

**Issue by be-cobblestone** [creativetimofficial/ct-paper-kit-pro#3]
I have a problem if notification classes are used together with bootstrap col... classes. The close button is moved out of the viewing field and falls off the screen when viewed on smaller screens (<768px)
See the attached example for more info
[4-content-areas-bug.html.zip](https://github.com/timcreative/paper-kit-pro/files/76324/4-content-areas-bug.html.zip)

**Comment by alexandru-paduraru** [comment]
@be-cobblestone thank you for pointing out. Can you please use "container-fluid" instead of "container" inside the ".alert" div? We will fix this on the product soon.

**Comment by be-cobblestone** [comment]
thanks, solved my problem

**Comment by alexandru-paduraru** [comment]
Issue fixed in V1.0.1 and is available for download on your dashboard on http://www.creative-tim.com

Thank you again for pointing out.
