### ISSUE TITLE
Problems with sidebar visibility with width 768px (iPad dimensions)

### ISSUE THREAD

**Issue by pawprosk** [creativetimofficial/ct-paper-kit-pro#6]
Hi, I found problem with sidebar - it's rather small problem as it occurs only for specific width (768px) - but as iPad 2 air has exactly same width it's quite disturbing.

To reproduce the problem please resize you material pro demo to 768 to see the problem.

-- 
And one small question - is it possible to easily implement off-canvas similar to material dashboard?

**Comment by alexandru-paduraru** [comment]
@pawprosk thank you for using our product. Can you please let us know which product you have? This is the repo for Paper Kit PRO and you are giving us an information about Material Pro (we have 2 Material products, [Material Kit Pro](https://www.creative-tim.com/product/material-kit-pro) and [Material Dashboard Pro](https://www.creative-tim.com/product/material-dashboard-pro) ). 

For Material Kit there is a known issue for the iPad and here is a solution https://github.com/creativetimofficial/material-kit-pro/issues/16

Hope this helps. Please let us know exactly what product you have and we will see how we can further assist.

Best,
Alex

**Comment by pawprosk** [comment]
@alexandru-paduraru thanks for reply.

I have both Material Pro (which contains the problem) and Material Dashboard Pro which has got other type of sidebar (push-canvas) and works fine on all devices.

I'll check the solution from mentioned link and give it a try later this day. 

--
Pawel

**Comment by pawprosk** [comment]
Yes the solution you mentioned helped. Thanks very much
